version: "3"

services:
  bot:
    build:
      context: "."
      dockerfile: Dockerfile
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    volumes:
      - "/codebase:/codebase"
      - "/storage:/storage"
    restart: always
